cargo-features = ["edition"]

[package]
name = "rlox-tokenizer"
version = "0.1.0"
authors = ["ben01189998819991197253 <dev.ben01189998819991197253@gmail.com>"]
edition = "2018"

[dependencies]
"unicode-segmentation" = "1.2"
